version: '3'
services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    container_name: rabbitmq1
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'supersecretcookie'
      RABBITMQ_NODENAME: rabbit@rabbitmq1
    networks:
      - rabbitnet

  rabbitmq2:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    hostname: rabbitmq2
    container_name: rabbitmq2
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'supersecretcookie'
      RABBITMQ_NODENAME: rabbit@rabbitmq2
    depends_on:
      - rabbitmq1
    networks:
      - rabbitnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foro-backend
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq1
    environment:
      SPRING_PROFILES_ACTIVE: default
    networks:
      - rabbitnet

networks:
  rabbitnet:
    driver: bridge
