FROM rabbitmq:3-management

# Instalar netcat (openbsd) en Debian-based image
USER root
RUN apt-get update && apt-get install -y netcat-openbsd

COPY rabbitmq-entrypoint.sh /rabbitmq-entrypoint.sh
RUN chmod +x /rabbitmq-entrypoint.sh

ENTRYPOINT ["/rabbitmq-entrypoint.sh"]
